-- ─────────────────────────────────────────────────────────────────────────────
-- Migration: 001_initial_schema.sql
-- Project:   B2B Voice Agent – TalentFlow (Everlast Challenge 2026)
-- Created:   2026-02-28
-- ─────────────────────────────────────────────────────────────────────────────

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: leads
-- Stores all lead profiles captured during or after a call
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS leads (
  id                UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Contact info
  name              TEXT,
  email             TEXT,
  phone             TEXT,
  company           TEXT,
  job_title         TEXT,

  -- Company profile
  company_size      INT,                          -- number of employees
  industry          TEXT,
  region            TEXT DEFAULT 'DACH',

  -- Lead grade & score
  lead_grade        CHAR(1) CHECK (lead_grade IN ('A', 'B', 'C')),
  lead_score        SMALLINT CHECK (lead_score BETWEEN 0 AND 100),

  -- BANT+ scores (0–25 / 0–25 / 0–25 / 0–15 / 0–10)
  score_budget      SMALLINT DEFAULT 0,
  score_authority   SMALLINT DEFAULT 0,
  score_need        SMALLINT DEFAULT 0,
  score_timeline    SMALLINT DEFAULT 0,
  score_fit         SMALLINT DEFAULT 0,

  -- Qualification notes
  pain_points       TEXT[],
  objections        TEXT[],
  notes             TEXT,

  -- Status
  status            TEXT DEFAULT 'new'
                    CHECK (status IN ('new', 'nurturing', 'demo_scheduled', 'demo_done', 'won', 'lost')),

  -- Booked demo
  demo_booked_at    TIMESTAMPTZ,
  demo_slot         TIMESTAMPTZ,
  calcom_booking_id TEXT
);

CREATE INDEX idx_leads_grade       ON leads(lead_grade);
CREATE INDEX idx_leads_status      ON leads(status);
CREATE INDEX idx_leads_created_at  ON leads(created_at DESC);

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: calls
-- One row per Vapi call session
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS calls (
  id                    UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Vapi identifiers
  vapi_call_id          TEXT UNIQUE NOT NULL,
  vapi_assistant_id     TEXT,
  phone_number_from     TEXT,
  phone_number_to       TEXT,

  -- Timing
  call_started_at       TIMESTAMPTZ,
  call_ended_at         TIMESTAMPTZ,
  duration_seconds      INT,

  -- Outcome
  status                TEXT DEFAULT 'initiated'
                        CHECK (status IN ('initiated', 'in_progress', 'completed', 'failed', 'no_answer')),
  end_reason            TEXT,                    -- e.g. 'hangup', 'silence_timeout', 'max_duration'

  -- Lead link
  lead_id               UUID REFERENCES leads(id) ON DELETE SET NULL,

  -- Conversation phases tracking
  phases_completed      TEXT[],
  drop_off_phase        TEXT,                    -- phase where lead hung up

  -- Avg response latency from Vapi telemetry
  avg_latency_ms        INT,

  -- Recording
  recording_url         TEXT,
  transcript_url        TEXT,

  -- Post-call summary (generated by Claude)
  summary               JSONB,                  -- full structured summary from system prompt

  -- Raw Vapi event payload (for debugging)
  raw_payload           JSONB
);

CREATE INDEX idx_calls_lead_id      ON calls(lead_id);
CREATE INDEX idx_calls_started_at   ON calls(call_started_at DESC);
CREATE INDEX idx_calls_status       ON calls(status);
CREATE INDEX idx_calls_vapi_call_id ON calls(vapi_call_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: call_events
-- Fine-grained event log per call (for funnel / drop-off analysis)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS call_events (
  id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  call_id       UUID NOT NULL REFERENCES calls(id) ON DELETE CASCADE,
  event_type    TEXT NOT NULL,          -- e.g. 'phase_started', 'phase_completed', 'objection', 'tool_call', 'booking_created'
  phase         TEXT,                   -- which conversation phase this event belongs to
  payload       JSONB,                  -- event-specific data
  latency_ms    INT                     -- response latency at time of event (from Vapi)
);

CREATE INDEX idx_call_events_call_id    ON call_events(call_id);
CREATE INDEX idx_call_events_type       ON call_events(event_type);
CREATE INDEX idx_call_events_created_at ON call_events(created_at DESC);

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: bookings
-- Confirmed Cal.com demo bookings
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS bookings (
  id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  lead_id             UUID REFERENCES leads(id) ON DELETE SET NULL,
  call_id             UUID REFERENCES calls(id) ON DELETE SET NULL,

  calcom_booking_id   TEXT UNIQUE NOT NULL,
  calcom_booking_uid  TEXT,
  scheduled_at        TIMESTAMPTZ NOT NULL,
  duration_minutes    INT DEFAULT 30,

  -- Attendee details (snapshot at booking time)
  attendee_name       TEXT,
  attendee_email      TEXT NOT NULL,
  attendee_company    TEXT,

  -- Status tracking
  status              TEXT DEFAULT 'confirmed'
                      CHECK (status IN ('confirmed', 'cancelled', 'rescheduled', 'no_show', 'completed')),
  cancelled_at        TIMESTAMPTZ,
  cancellation_reason TEXT
);

CREATE INDEX idx_bookings_lead_id      ON bookings(lead_id);
CREATE INDEX idx_bookings_scheduled_at ON bookings(scheduled_at DESC);
CREATE INDEX idx_bookings_status       ON bookings(status);

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: kpi_snapshots
-- Hourly/daily KPI snapshots for dashboard time-series charts
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS kpi_snapshots (
  id                    UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  snapshot_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  period                TEXT NOT NULL CHECK (period IN ('hourly', 'daily')),

  total_calls           INT DEFAULT 0,
  completed_calls       INT DEFAULT 0,
  conversion_rate       NUMERIC(5,2),     -- percent: bookings / completed_calls
  avg_call_duration_sec INT,
  avg_latency_ms        INT,

  leads_a               INT DEFAULT 0,
  leads_b               INT DEFAULT 0,
  leads_c               INT DEFAULT 0,

  bookings_confirmed    INT DEFAULT 0,
  bookings_no_show      INT DEFAULT 0,

  top_drop_off_phase    TEXT
);

CREATE INDEX idx_kpi_snapshot_at ON kpi_snapshots(snapshot_at DESC);

-- ─────────────────────────────────────────────────────────────────────────────
-- FUNCTION: auto-update updated_at timestamp
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER leads_updated_at
  BEFORE UPDATE ON leads
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ─────────────────────────────────────────────────────────────────────────────
-- VIEW: dashboard_calls_summary
-- Convenient view for dashboard queries
-- ─────────────────────────────────────────────────────────────────────────────
-- SECURITY DEFINER view: anon can read aggregated dashboard data
-- without direct access to leads/bookings tables (PII protection)
-- Only exposes name, company, grade — NOT email, phone, or full PII
CREATE OR REPLACE VIEW dashboard_calls_summary
  WITH (security_invoker = false)
AS
SELECT
  c.id,
  c.vapi_call_id,
  c.call_started_at,
  c.duration_seconds,
  c.status,
  c.drop_off_phase,
  c.avg_latency_ms,
  l.name            AS lead_name,
  l.company         AS lead_company,
  l.lead_grade,
  l.lead_score,
  b.scheduled_at    AS demo_scheduled_at,
  b.status          AS booking_status
FROM calls c
LEFT JOIN leads   l ON l.id = c.lead_id
LEFT JOIN bookings b ON b.call_id = c.id
ORDER BY c.call_started_at DESC;

-- ─────────────────────────────────────────────────────────────────────────────
-- ROW LEVEL SECURITY (enable for production)
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE leads         ENABLE ROW LEVEL SECURITY;
ALTER TABLE calls         ENABLE ROW LEVEL SECURITY;
ALTER TABLE call_events   ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings      ENABLE ROW LEVEL SECURITY;
ALTER TABLE kpi_snapshots ENABLE ROW LEVEL SECURITY;

-- Allow service role full access (used by webhook server)
CREATE POLICY "service_role_all" ON leads         FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "service_role_all" ON calls         FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "service_role_all" ON call_events   FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "service_role_all" ON bookings      FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "service_role_all" ON kpi_snapshots FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Allow anon key read-only access for dashboard
-- Note: leads and bookings contain PII (email, phone, name) — restrict columns via view
-- anon can only read aggregated/non-PII data; the dashboard view filters sensitive fields
CREATE POLICY "anon_read" ON calls         FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read" ON call_events   FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read" ON kpi_snapshots FOR SELECT TO anon USING (true);

-- leads & bookings: anon can only read through the dashboard_calls_summary view
-- Direct table access is denied — the view runs with the definer's privileges
CREATE POLICY "anon_read" ON leads    FOR SELECT TO anon USING (false);
CREATE POLICY "anon_read" ON bookings FOR SELECT TO anon USING (false);
